# Synthese Vocale Wolof & Francais

Pipeline simplifie avec SpeechT5, suppression de grincements et voix fluide.

## 1. Installation

In [20]:
#!pip install transformers torch torchaudio speechbrain soundfile scipy PyWavelets

## 2. HF_TOKEN (optionnel)

In [3]:
import os
# from google.colab import userdata
# os.environ['HF_TOKEN'] = userdata.get('HF_TOKEN')

## 3. Initialisation du TTS

Charge les modeles et extrait le speaker embedding depuis `audio.wav`.

In [24]:
from tts import TTS

tts = TTS(audio_path="audio.wav")

Device: cpu


Loading weights: 100%|██████████| 396/396 [00:00<00:00, 12414.10it/s]
[transformers] You are using a model of type `hifigan` to instantiate a model of type `speecht5_hifigan`. This may be expected if you are loading a checkpoint that shares a subset of the architecture (e.g., loading a `sam2_video` checkpoint into `Sam2Model`), but is otherwise not supported and can yield errors. Please verify that the checkpoint is compatible with the model you are instantiating.
Loading weights: 100%|██████████| 158/158 [00:00<00:00, 27288.45it/s]

Speaker embedding chargé depuis audio.wav (torch.Size([1, 512]))


## 4. Generation

Parametres pour reduire le grincement :
- `temperature=0.5` : plus stable, moins d'artefacts
- `num_beams=16` : recherche plus large
- `repetition_penalty=1.5` : evite les motifs repetitifs

In [30]:
tts.play("aksel waaaaaay", temperature=0.5, num_beams=16, repetition_penalty=1.5)

array([1.60892223e-08, 1.68969323e-07, 7.93601820e-07, ...,
       3.42204273e-03, 3.00727101e-03, 2.75637215e-03], shape=(37888,))

In [29]:
tts.play("Bonjour, bienvenue dans le modele de synthese vocale.", temperature=0.5, num_beams=16, repetition_penalty=1.5)

array([ 1.59994113e-08,  1.68026127e-07,  7.89171890e-07, ...,
       -3.24131337e-07, -3.41522684e-07, -3.58548859e-07], shape=(74752,))

In [28]:
tts.play("damaa beuga dem sama ker wayé yoon bi dafa meti", temperature=0.5, num_beams=16, repetition_penalty=1.5)

array([1.60407133e-08, 1.68459881e-07, 7.91209112e-07, ...,
       6.91034612e-05, 6.83023562e-05, 6.73907433e-05], shape=(93696,))

## 5. Sauvegarder un audio

In [8]:
tts.generate("Bopou louminaa dafa reuy", output_path="output.wav", temperature=0.8, num_beams=16, repetition_penalty=1.5)

Audio sauvegardé: output.wav


array([ 1.60024800e-08,  1.68058355e-07,  7.89323254e-07, ...,
       -5.61677969e-04, -3.94562978e-04, -3.04546240e-04], shape=(46080,))

In [12]:
tts.generate("dama beuga dem sama ker", output_path="output.wav", temperature=0.8, num_beams=16, repetition_penalty=1.5)

Audio sauvegardé: output.wav


array([ 1.60276780e-08,  1.68322985e-07,  7.90566147e-07, ...,
        9.41780914e-06,  1.33092940e-06, -6.06273390e-06], shape=(66048,))