# Synthese Vocale Wolof & Francais

Pipeline simplifie avec SpeechT5, suppression de grincements et voix fluide.

## 1. Installation

In [2]:
!pip install transformers torch torchaudio speechbrain soundfile scipy PyWavelets

## 2. HF_TOKEN (optionnel)

In [3]:
import os
# from google.colab import userdata
# os.environ['HF_TOKEN'] = userdata.get('HF_TOKEN')

## 3. Initialisation du TTS

Charge les modeles et extrait le speaker embedding depuis `audio.wav`.

In [4]:
from tts import TTS

tts = TTS(audio_path="audio.wav")

/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Device: cpu


Loading weights: 100%|██████████| 396/396 [00:00<00:00, 5731.05it/s]
[transformers] You are using a model of type `hifigan` to instantiate a model of type `speecht5_hifigan`. This may be expected if you are loading a checkpoint that shares a subset of the architecture (e.g., loading a `sam2_video` checkpoint into `Sam2Model`), but is otherwise not supported and can yield errors. Please verify that the checkpoint is compatible with the model you are instantiating.
Loading weights: 100%|██████████| 158/158 [00:00<00:00, 52775.35it/s]

Speaker embedding chargé depuis audio.wav (torch.Size([1, 512]))


## 4. Generation

Parametres pour reduire le grincement :
- `temperature=0.5` : plus stable, moins d'artefacts
- `num_beams=16` : recherche plus large
- `repetition_penalty=1.5` : evite les motifs repetitifs

In [5]:
tts.play("aksel waaaaaay", temperature=0.5, num_beams=16, repetition_penalty=1.5)

array([1.60630078e-08, 1.68694019e-07, 7.92308790e-07, ...,
       5.34524981e-03, 9.29316411e-03, 1.08894242e-02], shape=(40448,))

In [6]:
tts.play("Bonjour, bienvenue dans le modele de synthese vocale.", temperature=0.5, num_beams=16, repetition_penalty=1.5)

array([ 1.59920478e-08,  1.67948795e-07,  7.88808682e-07, ...,
       -2.47374795e-04, -2.49484753e-04, -2.49767788e-04], shape=(76800,))

In [19]:
tts.play("damaa beuga dem sama ker wayé yoon bi dafa meti", temperature=0.8, num_beams=16, repetition_penalty=1.5)

array([ 1.60406379e-08,  1.68459090e-07,  7.91205394e-07, ...,
       -1.14096038e-03, -1.19172603e-03, -1.18200161e-03], shape=(118272,))

## 5. Sauvegarder un audio

In [8]:
tts.generate("Bopou louminaa dafa reuy", output_path="output.wav", temperature=0.8, num_beams=16, repetition_penalty=1.5)

Audio sauvegardé: output.wav


array([ 1.60024800e-08,  1.68058355e-07,  7.89323254e-07, ...,
       -5.61677969e-04, -3.94562978e-04, -3.04546240e-04], shape=(46080,))

In [12]:
tts.generate("dama beuga dem sama ker", output_path="output.wav", temperature=0.8, num_beams=16, repetition_penalty=1.5)

Audio sauvegardé: output.wav


array([ 1.60276780e-08,  1.68322985e-07,  7.90566147e-07, ...,
        9.41780914e-06,  1.33092940e-06, -6.06273390e-06], shape=(66048,))